-- Insert 100 frameworks into master_4500 table for The Thinking Engine
-- Each framework starts as 'scaffold' status with 0 progress

INSERT INTO public.master_4500 (
  book_slug, section_slug, exemplar_type, title, status, progress, 
  description, core_framework, notes
) VALUES
  ('thinking-engine', 'frameworks', 'framework', 'Free Energy Principle', 'scaffold', 0, 'prediction error minimisation', 'Signal', 'Neuroscience foundation for BCI signal processing'),
  ('thinking-engine', 'frameworks', 'framework', 'Active Inference', 'scaffold', 0, 'action = perception updates', 'Signal/Human', 'Translating neural intent into adaptive behaviours'),
  ('thinking-engine', 'frameworks', 'framework', 'Hebbian Learning', 'scaffold', 0, 'neurons that fire together wire together', 'Signal', 'Neuroplasticity models in rehab'),
  ('thinking-engine', 'frameworks', 'framework', 'Neural Darwinism', 'scaffold', 0, 'selection of neural circuits', 'Signal', 'Explaining variability in outcomes'),
  ('thinking-engine', 'frameworks', 'framework', 'Network Neuroscience', 'scaffold', 0, 'brain as graph', 'Signal', 'Mapping neural connectivity changes'),
  ('thinking-engine', 'frameworks', 'framework', 'Biopsychosocial Model', 'scaffold', 0, 'mind–body–society', 'Human', 'Holistic patient framing'),
  ('thinking-engine', 'frameworks', 'framework', 'Self-Organised Criticality', 'scaffold', 0, 'power-law cascades', 'Signal/Loop', 'Understanding instability events in neural systems'),
  ('thinking-engine', 'frameworks', 'framework', 'Panarchy (Adaptive Cycle)', 'scaffold', 0, 'growth–conservation–release–reorg', 'Society/Loop', 'Renewal cycles in health systems and policy'),
  ('thinking-engine', 'frameworks', 'framework', 'Complex Adaptive Systems', 'scaffold', 0, 'agents + emergence', 'Human/Org', 'Modelling behaviour across actors'),
  ('thinking-engine', 'frameworks', 'framework', 'Cynefin', 'scaffold', 0, 'sense–categorise–probe–respond', 'Org/Society', 'Decision modes under uncertainty'),
  ('thinking-engine', 'frameworks', 'framework', 'S-Curve / Sigmoid', 'scaffold', 0, 'slow–fast–plateau', 'Loop', 'Tech adoption, team growth phases'),
  ('thinking-engine', 'frameworks', 'framework', 'Diffusion of Innovations', 'scaffold', 0, 'innovators to laggards', 'Society', 'Market/regulator adoption of neurotech'),
  ('thinking-engine', 'frameworks', 'framework', 'Learning Health System', 'scaffold', 0, 'data → evidence → practice loop', 'Org/Loop', 'Continuous clinical feedback'),
  ('thinking-engine', 'frameworks', 'framework', 'OODA Loop', 'scaffold', 0, 'observe–orient–decide–act', 'Org/Human', 'Warfighter & crisis decisions'),
  ('thinking-engine', 'frameworks', 'framework', 'Systems Thinking (Meadows)', 'scaffold', 0, 'leverage points', 'Society/Loop', 'Understanding feedback structures'),
  ('thinking-engine', 'frameworks', 'framework', 'Resilience Engineering', 'scaffold', 0, 'anticipate–monitor–respond–learn', 'Org/Society', 'Safety and adaptation in deployment'),
  ('thinking-engine', 'frameworks', 'framework', 'High Reliability Org (HRO)', 'scaffold', 0, 'mindful organising', 'Org', 'Hospitals & defence ops safety culture'),
  ('thinking-engine', 'frameworks', 'framework', 'Dynamic Capabilities (Teece)', 'scaffold', 0, 'sense–seize–reconfigure', 'Org', 'Strategic pivots in companies'),
  ('thinking-engine', 'frameworks', 'framework', 'Core–Edge Innovation', 'scaffold', 0, 'adjacent markets', 'Org/Society', 'Expanding new BCI use cases'),
  ('thinking-engine', 'frameworks', 'framework', 'Spiral Dynamics', 'scaffold', 0, 'value systems evolution', 'Human/Society', 'Cultural adoption patterns'),
  ('thinking-engine', 'frameworks', 'framework', 'Integral Theory (Wilber)', 'scaffold', 0, 'quadrants & levels', 'Society', 'Framing cross-perspectives'),
  ('thinking-engine', 'frameworks', 'framework', 'Antifragility (Taleb)', 'scaffold', 0, 'gain from disorder', 'Org/Loop', 'Designing systems to strengthen under stress'),
  ('thinking-engine', 'frameworks', 'framework', 'Appreciative Inquiry', 'scaffold', 0, 'positive change lens', 'Human/Org', 'Culture and adoption programs'),
  ('thinking-engine', 'frameworks', 'framework', 'Kotter 8 Steps', 'scaffold', 0, 'burning platform to anchor change', 'Org', 'Change programs in hospitals or defence'),
  ('thinking-engine', 'frameworks', 'framework', 'Prosci ADKAR', 'scaffold', 0, 'awareness, desire, knowledge, ability, reinforcement', 'Human/Org', 'Individual adoption of BCIs'),
  ('thinking-engine', 'frameworks', 'framework', 'McKinsey 7-S', 'scaffold', 0, 'structure, systems, staff, style, skills, strategy, shared values', 'Org', 'Org alignment pre-deployment'),
  ('thinking-engine', 'frameworks', 'framework', 'Viable System Model (Beer)', 'scaffold', 0, 'recursion and viability', 'Org', 'Structuring large complex orgs'),
  ('thinking-engine', 'frameworks', 'framework', 'Stakeholder Theory (Freeman)', 'scaffold', 0, 'stakeholders = central', 'Org/Society', 'Multi-party alignment (regulators, patients, military)'),
  ('thinking-engine', 'frameworks', 'framework', 'Public Value Framework', 'scaffold', 0, 'create, measure, sustain', 'Society', 'Justifying public funding of BCI'),
  ('thinking-engine', 'frameworks', 'framework', 'Commons Theory (Ostrom)', 'scaffold', 0, 'governance of shared resources', 'Society', 'Shared datasets, neurocommons'),
  ('thinking-engine', 'frameworks', 'framework', 'Game Theory (Nash)', 'scaffold', 0, 'strategy equilibrium', 'Org/Society', 'Negotiation in defence/insurer contexts'),
  ('thinking-engine', 'frameworks', 'framework', 'Trust Game', 'scaffold', 0, 'repeated cooperation/defection', 'Human/Society', 'Patient trust modelling'),
  ('thinking-engine', 'frameworks', 'framework', 'Principal–Agent Problem', 'scaffold', 0, 'misaligned incentives', 'Org', 'Insurer vs patient vs provider'),
  ('thinking-engine', 'frameworks', 'framework', 'Belmont Report', 'scaffold', 0, 'respect, beneficence, justice', 'Human/Society', 'Bioethics anchor'),
  ('thinking-engine', 'frameworks', 'framework', 'Triple Bottom Line', 'scaffold', 0, 'people, planet, profit', 'Society', 'ESG framing of BCI'),
  ('thinking-engine', 'frameworks', 'framework', 'Doughnut Economics (Raworth)', 'scaffold', 0, 'safe & just operating space', 'Society', 'Policy balance adoption vs risk'),
  ('thinking-engine', 'frameworks', 'framework', 'ESG / B-Corp Principles', 'scaffold', 0, 'stakeholder balance', 'Org/Society', 'Ethics in scale-up phase'),
  ('thinking-engine', 'frameworks', 'framework', 'Gartner Hype Cycle', 'scaffold', 0, 'inflated expectations curve', 'Loop', 'Positioning BCI tech maturity'),
  ('thinking-engine', 'frameworks', 'framework', 'Technology Readiness Levels (TRL)', 'scaffold', 0, 'TRL 1–9', 'Org', 'Clinical trial maturity assessment'),
  ('thinking-engine', 'frameworks', 'framework', 'Horizon Scanning', 'scaffold', 0, 'foresight methods', 'Society', 'Long-range planning for BCI impact'),
  ('thinking-engine', 'frameworks', 'framework', 'Blue Ocean Strategy', 'scaffold', 0, 'uncontested market space', 'Org', 'Finding novel BCI niches'),
  ('thinking-engine', 'frameworks', 'framework', 'Christensen Disruption', 'scaffold', 0, 'low-end disruptor wins', 'Org', 'New entrant strategy'),
  ('thinking-engine', 'frameworks', 'framework', 'Porter''s Value Chain', 'scaffold', 0, 'primary + support activities', 'Org', 'BCI ecosystem mapping'),
  ('thinking-engine', 'frameworks', 'framework', 'Platform Economy Models', 'scaffold', 0, 'value grows with users', 'Society', 'Neurotech ecosystems'),
  ('thinking-engine', 'frameworks', 'framework', 'Network Effects', 'scaffold', 0, 'more users = more value', 'Society', 'Scaling adoption of neural data standards'),
  ('thinking-engine', 'frameworks', 'framework', 'Metcalfe''s Law', 'scaffold', 0, 'value ∝ n²', 'Society', 'Quantifying BCI network growth'),
  ('thinking-engine', 'frameworks', 'framework', 'Jevons Paradox', 'scaffold', 0, 'efficiency → more consumption', 'Loop', 'Warning on rebound effects'),
  ('thinking-engine', 'frameworks', 'framework', 'Amara''s Law', 'scaffold', 0, 'we over/underestimate tech', 'Society', 'Framing expectations'),
  ('thinking-engine', 'frameworks', 'framework', 'Belmont 2.0 (extended ethics)', 'scaffold', 0, 'fairness, autonomy, inclusivity', 'Human', 'Updated AI ethics context'),
  ('thinking-engine', 'frameworks', 'framework', 'IEEE Ethically Aligned Design', 'scaffold', 0, 'standardised AI ethics', 'Org/Society', 'Technical alignment'),
  ('thinking-engine', 'frameworks', 'framework', 'UNESCO AI Ethics', 'scaffold', 0, 'global AI ethics principles', 'Society', 'UN framing for adoption'),
  ('thinking-engine', 'frameworks', 'framework', 'OECD AI Principles', 'scaffold', 0, 'responsible AI adoption', 'Society', 'OECD policy framing'),
  ('thinking-engine', 'frameworks', 'framework', 'Responsible Innovation (Stilgoe)', 'scaffold', 0, 'anticipate–reflect–engage–act', 'Org/Society', 'Embedding reflexivity'),
  ('thinking-engine', 'frameworks', 'framework', 'FAT ML Principles', 'scaffold', 0, 'fairness, accountability, transparency', 'Human/Org', 'Trustworthy ML integration'),
  ('thinking-engine', 'frameworks', 'framework', 'Algorithmic Accountability', 'scaffold', 0, 'audit trails', 'Org', 'Compliance in deployments'),
  ('thinking-engine', 'frameworks', 'framework', 'Differential Privacy', 'scaffold', 0, 'noise injection', 'Signal/Org', 'Protecting patient data'),
  ('thinking-engine', 'frameworks', 'framework', 'Human-in-the-Loop AI', 'scaffold', 0, 'keep human control', 'Human/Org', 'Clinical & defence safeguards'),
  ('thinking-engine', 'frameworks', 'framework', 'Continuous Learning Culture (SAFe)', 'scaffold', 0, 'inspect & adapt', 'Org', 'Agile adoption culture'),
  ('thinking-engine', 'frameworks', 'framework', 'DevOps CALMS', 'scaffold', 0, 'culture, automation, lean, measurement, sharing', 'Org', 'IT operations integration'),
  ('thinking-engine', 'frameworks', 'framework', 'SRE (Google)', 'scaffold', 0, 'error budgets', 'Org', 'Service reliability for neurocloud'),
  ('thinking-engine', 'frameworks', 'framework', 'ITIL v3/v4', 'scaffold', 0, 'IT service mgmt', 'Org', 'Baseline language for ops'),
  ('thinking-engine', 'frameworks', 'framework', 'SIAM', 'scaffold', 0, 'service integration', 'Org', 'Multi-vendor orchestration'),
  ('thinking-engine', 'frameworks', 'framework', 'COBIT', 'scaffold', 0, 'IT governance', 'Org', 'Compliance structures'),
  ('thinking-engine', 'frameworks', 'framework', 'ISO 38500', 'scaffold', 0, 'IT governance', 'Org', 'Board oversight'),
  ('thinking-engine', 'frameworks', 'framework', 'TOGAF', 'scaffold', 0, 'enterprise architecture', 'Org', 'Blueprinting ecosystems'),
  ('thinking-engine', 'frameworks', 'framework', 'IT4IT', 'scaffold', 0, 'value chain for IT', 'Org', 'IT operating model reference'),
  ('thinking-engine', 'frameworks', 'framework', 'NIST Cybersecurity Framework', 'scaffold', 0, 'identify–protect–detect–respond–recover', 'Org', 'Cyber baseline'),
  ('thinking-engine', 'frameworks', 'framework', 'Zero Trust', 'scaffold', 0, 'never trust, always verify', 'Org', 'Secure BCI deployments'),
  ('thinking-engine', 'frameworks', 'framework', 'Data Mesh', 'scaffold', 0, 'decentralised data ownership', 'Org', 'BCI signal governance'),
  ('thinking-engine', 'frameworks', 'framework', 'Data Fabric', 'scaffold', 0, 'unified data layer', 'Org', 'Integration strategy'),
  ('thinking-engine', 'frameworks', 'framework', 'Open Innovation', 'scaffold', 0, 'share external knowledge', 'Org/Society', 'Collaboration models'),
  ('thinking-engine', 'frameworks', 'framework', 'Knowledge Spiral (Nonaka)', 'scaffold', 0, 'tacit–explicit cycles', 'Org', 'Knowledge management'),
  ('thinking-engine', 'frameworks', 'framework', 'Design Thinking', 'scaffold', 0, 'empathise–define–ideate–prototype–test', 'Human/Org', 'Patient-centric design'),
  ('thinking-engine', 'frameworks', 'framework', 'Lean Startup', 'scaffold', 0, 'build–measure–learn', 'Org', 'Iterative innovation'),
  ('thinking-engine', 'frameworks', 'framework', 'Agile Manifesto', 'scaffold', 0, 'individuals & interactions', 'Org', 'Development mindset'),
  ('thinking-engine', 'frameworks', 'framework', 'SAFE (Scaled Agile)', 'scaffold', 0, 'portfolio-level agility', 'Org', 'Scaling programs'),
  ('thinking-engine', 'frameworks', 'framework', 'Kanban', 'scaffold', 0, 'flow, WIP limits', 'Org', 'Visualising clinical/ops work'),
  ('thinking-engine', 'frameworks', 'framework', 'Scrum', 'scaffold', 0, 'sprint cycles', 'Org', 'Agile execution'),
  ('thinking-engine', 'frameworks', 'framework', 'PRINCE2', 'scaffold', 0, 'structured project management', 'Org', 'Regulated project contexts'),
  ('thinking-engine', 'frameworks', 'framework', 'BABOK', 'scaffold', 0, 'business analysis', 'Org', 'Requirements capture'),
  ('thinking-engine', 'frameworks', 'framework', 'Six Sigma', 'scaffold', 0, 'reduce variation', 'Org', 'Process optimisation'),
  ('thinking-engine', 'frameworks', 'framework', 'Lean', 'scaffold', 0, 'eliminate waste', 'Org', 'Efficiency programs'),
  ('thinking-engine', 'frameworks', 'framework', 'TQM (Total Quality Mgmt)', 'scaffold', 0, 'continuous quality', 'Org', 'Quality culture'),
  ('thinking-engine', 'frameworks', 'framework', 'Balanced Scorecard', 'scaffold', 0, '4 perspectives', 'Org', 'Strategy execution'),
  ('thinking-engine', 'frameworks', 'framework', 'EFQM Model', 'scaffold', 0, 'excellence model', 'Org', 'Benchmarking'),
  ('thinking-engine', 'frameworks', 'framework', 'Kaizen', 'scaffold', 0, 'continuous small improvements', 'Org', 'Incremental change'),
  ('thinking-engine', 'frameworks', 'framework', 'OKRs', 'scaffold', 0, 'objectives & key results', 'Org', 'Aligning teams'),
  ('thinking-engine', 'frameworks', 'framework', 'KPI Frameworks', 'scaffold', 0, 'key indicators', 'Org', 'Measurement culture'),
  ('thinking-engine', 'frameworks', 'framework', 'Value Stream Mapping', 'scaffold', 0, 'flow diagrams', 'Org', 'Operations design'),
  ('thinking-engine', 'frameworks', 'framework', 'Hoshin Kanri', 'scaffold', 0, 'strategy deployment', 'Org', 'Long-term alignment'),
  ('thinking-engine', 'frameworks', 'framework', 'McKinsey Horizons', 'scaffold', 0, '3 horizons growth', 'Org/Society', 'Long-term innovation framing'),
  ('thinking-engine', 'frameworks', 'framework', 'Shell Scenarios', 'scaffold', 0, 'plausible futures', 'Society', 'Scenario planning'),
  ('thinking-engine', 'frameworks', 'framework', 'PESTEL', 'scaffold', 0, 'political, economic, social, tech, env, legal', 'Society', 'Macro scanning'),
  ('thinking-engine', 'frameworks', 'framework', 'SWOT', 'scaffold', 0, 'strengths, weaknesses, opportunities, threats', 'Org', 'Baseline analysis'),
  ('thinking-engine', 'frameworks', 'framework', 'Porter 5 Forces', 'scaffold', 0, 'industry rivalry', 'Org/Society', 'Competitive framing'),
  ('thinking-engine', 'frameworks', 'framework', 'BCG Matrix', 'scaffold', 0, 'stars, cash cows, dogs', 'Org', 'Portfolio mgmt'),
  ('thinking-engine', 'frameworks', 'framework', 'Ansoff Matrix', 'scaffold', 0, 'product–market growth', 'Org', 'Strategy lens'),
  ('thinking-engine', 'frameworks', 'framework', 'Tipping Point (Gladwell)', 'scaffold', 0, 'small change → big effect', 'Society', 'Framing adoption shifts'),
  ('thinking-engine', 'frameworks', 'framework', 'Black Swan (Taleb)', 'scaffold', 0, 'rare disruptive events', 'Society', 'Risk planning'),
  ('thinking-engine', 'frameworks', 'framework', 'Slow Science', 'scaffold', 0, 'resist speed', 'Society', 'Meta-critique of research tempo');