-- Seed all 50 thinker profiles: Daniel Kahneman with rich data, others with baseline
INSERT INTO public.thinker_profiles (
  thinker_name,
  summary,
  key_concepts,
  why_it_matters,
  ai_implications,
  recommended_practices,
  common_pitfalls,
  success_metrics,
  usage_prompts,
  practical_applications,
  related_thinkers,
  cross_era_relevance,
  metadata
) VALUES 
-- Daniel Kahneman: Rich curated profile
(
  'Daniel Kahneman',
  'Kahneman''s dual-process theory reveals that human cognition operates through two distinct systems: System 1 (fast, automatic, intuitive) and System 2 (slow, deliberate, analytical). This framework has profound implications for AI design, as it helps us understand both the cognitive biases we might accidentally embed in AI systems and how to create AI that complements rather than replaces human judgment. In the AI era, this becomes critical for designing human-AI collaboration that leverages the strengths of both systems.',
  ARRAY[
    'System 1 Thinking: Fast, automatic, pattern-based decisions that feel effortless',
    'System 2 Thinking: Slow, deliberate analysis requiring conscious mental effort',
    'Cognitive Biases: Systematic errors in thinking that affect decisions and judgments',
    'Prospect Theory: How people make decisions involving risk and uncertainty',
    'Loss Aversion: The tendency to prefer avoiding losses over acquiring equivalent gains',
    'Availability Heuristic: Judging probability by how easily examples come to mind',
    'Anchoring Bias: Over-relying on first piece of information encountered'
  ],
  'As AI systems become more sophisticated, understanding human cognitive limitations becomes essential for several reasons: (1) AI training data reflects human biases that can be amplified at scale, (2) Human-AI collaboration requires designing interfaces that work with, not against, human psychology, (3) Critical decisions still require human judgment, especially for high-stakes, value-laden choices, and (4) AI systems need to be designed to help humans make better decisions, not just faster ones.',
  ARRAY[
    'AI systems can simultaneously operate at both System 1 and System 2 speeds, potentially transcending human cognitive limitations',
    'However, they also risk inheriting and amplifying human biases present in training data',
    'The key is designing AI that enhances human decision-making by providing System 1 speed with System 2 accuracy',
    'AI must preserve human agency in critical choices and maintain awareness of when human judgment is essential'
  ],
  ARRAY[
    'Implement bias detection systems that monitor AI outputs for common human biases',
    'Design decision architectures with explicit System 1/System 2 pathways',
    'Create "judgment preservation modes" that require human input to maintain cognitive skills',
    'Use prospect theory principles in AI interface design to account for loss aversion',
    'Build in human oversight triggers for high-uncertainty or value-critical decisions',
    'Apply behavioral economics to create ethical AI recommendation systems',
    'Design choice architecture that preserves human agency while optimizing outcomes'
  ],
  ARRAY[
    'Assuming AI is immune to cognitive biases when it inherits them from training data',
    'Over-automating decisions that require human judgment and contextual understanding',
    'Ignoring loss aversion in AI recommendations, leading to user resistance',
    'Designing AI interfaces that work against human psychology rather than with it',
    'Failing to preserve human decision-making skills in AI-augmented environments',
    'Not accounting for availability bias in AI training data selection'
  ],
  ARRAY[
    'Bias detection rate: Percentage of cognitive biases caught before deployment',
    'Human override rate: Frequency humans choose different paths than AI recommendations',
    'Decision accuracy improvement: Measurable better outcomes with AI assistance',
    'Cognitive skill retention: Evidence humans maintain judgment capabilities',
    'User acceptance rate: How readily people adopt AI decision support',
    'Ethical compliance score: Adherence to behavioral economics principles in design'
  ],
  ARRAY[
    'How should we design AI decision architectures that leverage both System 1 and System 2 thinking?',
    'What cognitive biases are our AI systems inheriting from training data, and how do we detect them?',
    'How do we design "nudge architectures" for AI agents interacting with humans?',
    'What happens to human judgment when AI handles most System 1 processing?',
    'How do we apply prospect theory to AI risk assessment and resource allocation?',
    'What decision-making processes should remain exclusively human in an AI-dominant world?'
  ],
  ARRAY[
    'Audit existing AI systems for inherited cognitive biases using behavioral economics frameworks',
    'Design hybrid AI architectures with explicit System 1/System 2 pathways',  
    'Create post-cognitive AI systems that transcend human decision-making limitations while preserving human agency'
  ],
  ARRAY['Amos Tversky', 'Gerd Gigerenzer', 'Herbert Simon', 'Richard Thaler'],
  jsonb_build_object(
    'ai_relevance', 'Critical for understanding cognitive biases in AI systems and designing human-AI collaboration',
    'cross_era_relevance', 'Dual-process theory becomes foundation for hybrid decision architectures across all eras',
    'implementation_timeline', jsonb_build_object(
      'phase_1', 'Audit AI systems for cognitive biases and implement detection systems',
      'phase_2', 'Design hybrid architectures with System 1/2 pathways and human oversight',
      'phase_3', 'Develop post-cognitive AI that transcends human limitations while preserving agency'
    )
  ),
  jsonb_build_object(
    'source', 'curated',
    'method', 'manual-seed', 
    'seeded_at', now(),
    'quality_score', 5.0
  )
),
-- Remaining 49 thinkers: Baseline profiles
('Amos Tversky', 'Foundational work on cognitive biases and heuristics in decision-making under uncertainty.', ARRAY['Prospect theory', 'Cognitive heuristics', 'Decision biases'], 'Essential for understanding systematic errors in both human and AI decision processes.', ARRAY['AI can implement bias correction mechanisms', 'Heuristic-based AI models need careful validation'], ARRAY['Monitor for systematic biases in AI outputs'], ARRAY['Avoid replicating human cognitive limitations in AI systems'], ARRAY['Bias detection accuracy', 'Decision improvement metrics'], ARRAY['How do we correct for systematic biases in AI decision systems?'], ARRAY['Implement bias detection systems', 'Develop heuristic-aware AI'], ARRAY['Daniel Kahneman', 'Herbert Simon'], jsonb_build_object('ai_relevance', 'High - bias correction and decision science'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Gerd Gigerenzer', 'Simple heuristics and ecological rationality in decision-making.', ARRAY['Fast-and-frugal heuristics', 'Ecological rationality'], 'Shows how simple rules can outperform complex models in uncertain environments.', ARRAY['AI heuristics can exceed human performance', 'Challenges traditional rationality models'], ARRAY['Design AI with adaptive heuristics'], ARRAY['Over-complicating simple decision problems'], ARRAY['Heuristic effectiveness', 'Decision speed vs accuracy'], ARRAY['When should AI use simple heuristics vs complex analysis?'], ARRAY['Implement adaptive heuristic systems', 'Balance simplicity with accuracy'], ARRAY['Daniel Kahneman', 'Herbert Simon'], jsonb_build_object('ai_relevance', 'Medium - heuristic design'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Herbert Simon', 'Bounded rationality and satisficing in complex decision environments.', ARRAY['Bounded rationality', 'Satisficing'], 'Explains how cognitive limits shape decision-making strategies.', ARRAY['AI removes some cognitive bounds', 'Introduces new computational constraints'], ARRAY['Design AI with appropriate computational bounds'], ARRAY['Assuming unlimited AI computational resources'], ARRAY['Computational efficiency', 'Decision satisfaction levels'], ARRAY['How do we design AI satisficing strategies?'], ARRAY['Implement bounded AI decision systems', 'Optimize for satisficing over maximizing'], ARRAY['Daniel Kahneman', 'Gerd Gigerenzer'], jsonb_build_object('ai_relevance', 'Medium - decision architecture'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Gary Klein', 'Recognition-primed decision making and naturalistic decision research.', ARRAY['Recognition-primed decisions', 'Expertise development'], 'Shows how experts make rapid decisions through pattern recognition.', ARRAY['AI can simulate expert pattern recognition instantly', 'Challenges traditional training models'], ARRAY['Build pattern recognition into AI systems'], ARRAY['Ignoring domain expertise requirements'], ARRAY['Pattern recognition accuracy', 'Expert decision simulation'], ARRAY['How can AI replicate expert intuition?'], ARRAY['Implement expert pattern recognition', 'Develop AI expertise models'], ARRAY['Daniel Kahneman', 'Malcolm Gladwell'], jsonb_build_object('ai_relevance', 'High - pattern recognition'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Richard Thaler', 'Behavioral economics and nudge theory for choice architecture.', ARRAY['Nudge theory', 'Choice architecture', 'Behavioral insights'], 'Demonstrates how environment design influences decision outcomes.', ARRAY['AI enables hyper-personalized nudges', 'Raises ethical concerns about manipulation'], ARRAY['Design ethical AI choice architecture'], ARRAY['Manipulative nudging without consent'], ARRAY['Choice improvement outcomes', 'User agency preservation'], ARRAY['How do we design ethical AI nudging systems?'], ARRAY['Implement responsible nudge AI', 'Preserve user choice autonomy'], ARRAY['Daniel Kahneman', 'Amos Tversky'], jsonb_build_object('ai_relevance', 'High - behavioral AI design'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Donella Meadows', 'Systems thinking and leverage points for organizational change.', ARRAY['Systems archetypes', 'Leverage points', 'Mental models'], 'Identifies where interventions create maximum impact in complex systems.', ARRAY['AI can dynamically alter system leverage points', 'Enables real-time system optimization'], ARRAY['Design AI to identify and act on leverage points'], ARRAY['Missing systemic interactions and feedback loops'], ARRAY['System intervention effectiveness', 'Leverage point identification'], ARRAY['Where are the highest-leverage points for AI intervention?'], ARRAY['Map system leverage points', 'Implement systemic AI interventions'], ARRAY['Peter Senge', 'Jay Forrester'], jsonb_build_object('ai_relevance', 'High - systems optimization'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Peter Senge', 'Learning organizations and systems thinking methodologies.', ARRAY['Learning organizations', 'Systems thinking', 'Mental models'], 'Framework for building adaptive organizational capabilities.', ARRAY['AI accelerates organizational learning loops', 'Enables continuous adaptation'], ARRAY['Build AI-enhanced learning systems'], ARRAY['Over-automating human learning processes'], ARRAY['Learning acceleration', 'Adaptation speed'], ARRAY['How can AI accelerate organizational learning?'], ARRAY['Implement AI learning systems', 'Accelerate feedback loops'], ARRAY['Donella Meadows', 'Chris Argyris'], jsonb_build_object('ai_relevance', 'Medium - organizational learning'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Jay Forrester', 'System dynamics and complex system modeling approaches.', ARRAY['System dynamics', 'Feedback loops', 'Complex modeling'], 'Mathematical approach to understanding complex system behaviors.', ARRAY['AI enables continuous system simulation', 'Real-time governance adjustments'], ARRAY['Implement AI-driven system dynamics'], ARRAY['Over-simplifying complex system relationships'], ARRAY['Model prediction accuracy', 'System behavior optimization'], ARRAY['How can AI improve system dynamics modeling?'], ARRAY['Build AI system simulators', 'Implement continuous modeling'], ARRAY['Donella Meadows', 'Peter Senge'], jsonb_build_object('ai_relevance', 'Medium - system modeling'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Geoffrey West', 'Scaling laws in complex systems and urban environments.', ARRAY['Scaling laws', 'Network effects', 'Urban dynamics'], 'Mathematical principles governing growth and efficiency in complex systems.', ARRAY['AI disrupts traditional scaling models', 'Enables new forms of network organization'], ARRAY['Apply scaling principles to AI system design'], ARRAY['Ignoring non-linear scaling effects'], ARRAY['Scaling efficiency', 'Network optimization'], ARRAY['How do scaling laws apply to AI systems?'], ARRAY['Design scalable AI architectures', 'Optimize network effects'], ARRAY['Jane Jacobs', 'Geoffrey Moore'], jsonb_build_object('ai_relevance', 'Medium - scaling optimization'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Clayton Christensen', 'Disruptive innovation theory and market dynamics.', ARRAY['Disruptive innovation', 'Innovation dilemma'], 'Framework for understanding how new technologies transform markets.', ARRAY['AI accelerates disruption cycles', 'Changes innovation patterns'], ARRAY['Anticipate AI-driven disruption patterns'], ARRAY['Missing early disruption signals'], ARRAY['Disruption prediction accuracy', 'Innovation cycle speed'], ARRAY['How does AI change disruption patterns?'], ARRAY['Monitor AI disruption signals', 'Adapt to accelerated innovation'], ARRAY['Geoffrey Moore', 'Peter Drucker'], jsonb_build_object('ai_relevance', 'High - innovation strategy'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Everett Rogers', 'Innovation diffusion and technology adoption processes.', ARRAY['Diffusion of innovations', 'Adoption curves'], 'Model for how innovations spread through populations.', ARRAY['AI can skip traditional adoption stages', 'Embedded in workflows automatically'], ARRAY['Design AI for rapid adoption'], ARRAY['Ignoring adoption resistance factors'], ARRAY['Adoption rate', 'User acceptance'], ARRAY['How does AI change innovation diffusion?'], ARRAY['Accelerate AI adoption', 'Embed in existing workflows'], ARRAY['Geoffrey Moore', 'Clayton Christensen'], jsonb_build_object('ai_relevance', 'Medium - technology adoption'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Geoffrey Moore', 'Technology adoption lifecycle and crossing the chasm.', ARRAY['Technology adoption lifecycle', 'Crossing the chasm'], 'Strategy for moving innovations from early adopters to mainstream markets.', ARRAY['AI bridges adoption gaps', 'Personalized onboarding at scale'], ARRAY['Design AI to facilitate technology adoption'], ARRAY['Assuming uniform adoption patterns'], ARRAY['Market penetration', 'Adoption acceleration'], ARRAY['How can AI help cross the adoption chasm?'], ARRAY['Build AI adoption bridges', 'Personalize technology onboarding'], ARRAY['Clayton Christensen', 'Everett Rogers'], jsonb_build_object('ai_relevance', 'Medium - market strategy'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Peter Drucker', 'Management theory and knowledge worker productivity.', ARRAY['Management by objectives', 'Knowledge work'], 'Foundational principles of modern management and productivity.', ARRAY['AI redefines knowledge work', 'Changes productivity measures'], ARRAY['Redesign management for AI era'], ARRAY['Applying industrial age metrics to knowledge work'], ARRAY['Knowledge worker productivity', 'Management effectiveness'], ARRAY['How does AI change management principles?'], ARRAY['Adapt management for AI', 'Redefine productivity metrics'], ARRAY['Clayton Christensen', 'W. Edwards Deming'], jsonb_build_object('ai_relevance', 'High - management transformation'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('W. Edwards Deming', 'Total quality management and continuous improvement.', ARRAY['Total quality management', 'Statistical process control'], 'Systematic approach to quality and continuous improvement.', ARRAY['AI enables predictive quality control', 'Self-correcting processes'], ARRAY['Implement AI quality systems'], ARRAY['Over-relying on automation without human oversight'], ARRAY['Quality improvement rate', 'Process optimization'], ARRAY['How can AI enhance quality management?'], ARRAY['Build predictive quality systems', 'Implement continuous AI optimization'], ARRAY['Peter Drucker', 'Kaizen methodology'], jsonb_build_object('ai_relevance', 'Medium - quality systems'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('John Maynard Keynes', 'Macroeconomic theory and government intervention in markets.', ARRAY['Macroeconomics', 'Fiscal policy'], 'Economic theory on market regulation and government role.', ARRAY['AI alters employment models', 'Changes economic multipliers'], ARRAY['Consider AI impact on economic policy'], ARRAY['Ignoring AI-driven economic changes'], ARRAY['Economic stability', 'Employment metrics'], ARRAY['How does AI affect macroeconomic policy?'], ARRAY['Adapt fiscal policy for AI', 'Monitor employment impacts'], ARRAY['Friedrich Hayek', 'Elinor Ostrom'], jsonb_build_object('ai_relevance', 'Medium - economic policy'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Friedrich Hayek', 'Market mechanisms and decentralized decision-making.', ARRAY['Price signals', 'Spontaneous order'], 'Theory of how markets coordinate complex economic activity.', ARRAY['AI enables synthetic markets', 'Real-time micro-pricing'], ARRAY['Design AI market mechanisms'], ARRAY['Centralizing decisions that benefit from distribution'], ARRAY['Market efficiency', 'Price discovery accuracy'], ARRAY['How can AI improve market coordination?'], ARRAY['Implement AI market systems', 'Enable dynamic pricing'], ARRAY['John Maynard Keynes', 'Elinor Ostrom'], jsonb_build_object('ai_relevance', 'Medium - market design'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Michael Porter', 'Competitive strategy and value chain analysis.', ARRAY['Competitive advantage', 'Value chain'], 'Framework for building and maintaining competitive advantages.', ARRAY['Advantage shifts to orchestration', 'Changes competitive dynamics'], ARRAY['Redesign strategy for AI era'], ARRAY['Relying on traditional competitive moats'], ARRAY['Competitive position', 'Value creation'], ARRAY['How does AI change competitive strategy?'], ARRAY['Build AI-native competitive advantages', 'Redesign value chains'], ARRAY['Clayton Christensen', 'Geoffrey Moore'], jsonb_build_object('ai_relevance', 'High - competitive strategy'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Elinor Ostrom', 'Commons governance and collective action problems.', ARRAY['Commons governance', 'Collective action'], 'Framework for managing shared resources without tragedy.', ARRAY['AI manages commons automatically', 'Blurs public/private boundaries'], ARRAY['Design AI commons governance'], ARRAY['Ignoring stakeholder participation needs'], ARRAY['Commons sustainability', 'Stakeholder satisfaction'], ARRAY['How can AI improve commons governance?'], ARRAY['Implement AI resource management', 'Design digital commons'], ARRAY['John Rawls', 'Amartya Sen'], jsonb_build_object('ai_relevance', 'Medium - governance systems'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Malcolm Gladwell', 'Social tipping points and viral change dynamics.', ARRAY['Tipping points', 'Social epidemics'], 'Understanding how small changes create big impacts in social systems.', ARRAY['AI can manufacture tipping points', 'Algorithmic influence at scale'], ARRAY['Design responsible AI influence systems'], ARRAY['Manipulating social dynamics unethically'], ARRAY['Social impact measurement', 'Influence tracking'], ARRAY['How can AI create positive social tipping points?'], ARRAY['Build ethical influence AI', 'Monitor social dynamics'], ARRAY['Gary Klein', 'Marshall McLuhan'], jsonb_build_object('ai_relevance', 'Medium - social influence'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Shoshana Zuboff', 'Surveillance capitalism and data extraction economics.', ARRAY['Surveillance capitalism', 'Behavioral futures'], 'Critical analysis of data-driven business models and privacy.', ARRAY['AI deepens surveillance capabilities', 'Intensifies extraction models'], ARRAY['Design privacy-preserving AI'], ARRAY['Ignoring data rights and user agency'], ARRAY['Privacy protection', 'User agency preservation'], ARRAY['How do we prevent AI surveillance capitalism?'], ARRAY['Build privacy-first AI', 'Protect user data rights'], ARRAY['Hannah Arendt', 'Tim O''Reilly'], jsonb_build_object('ai_relevance', 'High - AI ethics and privacy'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Yuval Noah Harari', 'Historical patterns and future scenario analysis.', ARRAY['Historical patterns', 'Future narratives'], 'Long-term perspective on human development and technological change.', ARRAY['AI becomes active narrative-shaper', 'Accelerates historical change'], ARRAY['Consider long-term AI implications'], ARRAY['Short-term thinking about long-term technologies'], ARRAY['Historical perspective accuracy', 'Future scenario quality'], ARRAY['What are the long-term implications of AI?'], ARRAY['Develop historical AI perspectives', 'Plan for long-term scenarios'], ARRAY['Nick Bostrom', 'Ray Kurzweil'], jsonb_build_object('ai_relevance', 'Medium - future planning'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Jane Jacobs', 'Urban planning and bottom-up city development.', ARRAY['Urban design', 'Bottom-up order'], 'Principles of organic city development and community planning.', ARRAY['AI enables micro-planning', 'Real-time city optimization'], ARRAY['Design AI for urban optimization'], ARRAY['Over-planning organic urban processes'], ARRAY['Urban livability', 'Community satisfaction'], ARRAY['How can AI improve urban planning?'], ARRAY['Implement smart city AI', 'Optimize urban systems'], ARRAY['Geoffrey West', 'Christopher Alexander'], jsonb_build_object('ai_relevance', 'Medium - urban systems'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Erving Goffman', 'Social interaction and presentation of self.', ARRAY['Presentation of self', 'Social roles'], 'Theory of how people manage social impressions and interactions.', ARRAY['AI agents co-author social identity', 'Changes social interaction'], ARRAY['Design AI for authentic social interaction'], ARRAY['Ignoring social context and cultural nuance'], ARRAY['Social interaction quality', 'Authentic representation'], ARRAY['How do AI agents affect social identity?'], ARRAY['Build socially aware AI', 'Preserve authentic interaction'], ARRAY['Marshall McLuhan', 'Hannah Arendt'], jsonb_build_object('ai_relevance', 'Medium - social AI'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Marshall McLuhan', 'Media theory and technological determinism.', ARRAY['Medium is the message', 'Global village'], 'Understanding how communication technologies shape society and consciousness.', ARRAY['AI is both medium and message creator', 'Transforms communication'], ARRAY['Consider AI as transformative medium'], ARRAY['Ignoring media effects on cognition'], ARRAY['Communication effectiveness', 'Media impact measurement'], ARRAY['How does AI change the nature of communication?'], ARRAY['Design AI communication systems', 'Consider media effects'], ARRAY['Erving Goffman', 'Neil Postman'], jsonb_build_object('ai_relevance', 'Medium - communication systems'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Nick Bostrom', 'Existential risk and superintelligence scenarios.', ARRAY['Superintelligence', 'Existential risk'], 'Analysis of long-term AI risks and safety considerations.', ARRAY['Agentic AI accelerates timeline', 'Requires immediate safety measures'], ARRAY['Prioritize AI safety and alignment'], ARRAY['Underestimating AI development speed'], ARRAY['AI safety measures', 'Alignment verification'], ARRAY['How do we ensure AI remains beneficial?'], ARRAY['Implement AI safety protocols', 'Build aligned AI systems'], ARRAY['Yuval Noah Harari', 'Stuart Russell'], jsonb_build_object('ai_relevance', 'Critical - AI safety'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Ray Kurzweil', 'Technological singularity and exponential change.', ARRAY['Technological singularity', 'Exponential growth'], 'Theory of accelerating technological change and its implications.', ARRAY['AI agency steepens exponential curves', 'Accelerates convergence'], ARRAY['Prepare for exponential AI capabilities'], ARRAY['Linear thinking about exponential change'], ARRAY['Technology acceleration rate', 'Capability growth'], ARRAY['How do we navigate exponential AI development?'], ARRAY['Plan for exponential AI growth', 'Adapt to accelerating change'], ARRAY['Nick Bostrom', 'Vernor Vinge'], jsonb_build_object('ai_relevance', 'High - technological acceleration'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Kevin Kelly', 'Technology evolution and digital transformation.', ARRAY['Technology evolution', 'Digital transformation'], 'Understanding technology as an evolving force with inherent direction.', ARRAY['AI introduces non-human technological evolution', 'Accelerates digital transformation'], ARRAY['Design for technological co-evolution'], ARRAY['Resisting inevitable technological change'], ARRAY['Technology adaptation', 'Digital transformation success'], ARRAY['What technological changes are inevitable with AI?'], ARRAY['Embrace inevitable AI evolution', 'Guide technological development'], ARRAY['Tim O''Reilly', 'Ray Kurzweil'], jsonb_build_object('ai_relevance', 'Medium - technology strategy'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Tim O''Reilly', 'Platform economics and open source development.', ARRAY['Platform thinking', 'Open source'], 'Strategy for building and managing technology platforms and ecosystems.', ARRAY['AI is both platform and participant', 'Changes platform dynamics'], ARRAY['Design AI-native platforms'], ARRAY['Treating AI as traditional software'], ARRAY['Platform ecosystem health', 'Developer engagement'], ARRAY['How do we build AI platforms?'], ARRAY['Create AI platform ecosystems', 'Enable AI participation'], ARRAY['Kevin Kelly', 'Marc Andreessen'], jsonb_build_object('ai_relevance', 'Medium - platform strategy'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Vernor Vinge', 'Intelligence explosion and technological forecasting.', ARRAY['Intelligence explosion', 'Technological forecasting'], 'Theory of rapid recursive self-improvement in intelligence systems.', ARRAY['Agentic AI accelerates intelligence explosion', 'Enables recursive improvement'], ARRAY['Prepare for intelligence explosion scenarios'], ARRAY['Underestimating recursive improvement potential'], ARRAY['Intelligence growth rate', 'Improvement cycles'], ARRAY['How do we manage intelligence explosion?'], ARRAY['Plan for rapid AI improvement', 'Control recursive development'], ARRAY['Ray Kurzweil', 'Nick Bostrom'], jsonb_build_object('ai_relevance', 'Critical - AI development'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Isaiah Berlin', 'Value pluralism and competing ethical frameworks.', ARRAY['Value pluralism', 'Liberty concepts'], 'Theory of irreducible conflicts between competing values and freedoms.', ARRAY['AI can embody conflicting values simultaneously', 'Requires value alignment'], ARRAY['Design AI for value pluralism'], ARRAY['Assuming universal value consensus'], ARRAY['Value representation', 'Ethical consistency'], ARRAY['How do we handle conflicting values in AI?'], ARRAY['Build pluralistic AI systems', 'Handle value conflicts'], ARRAY['John Rawls', 'Martha Nussbaum'], jsonb_build_object('ai_relevance', 'High - AI ethics'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('John Rawls', 'Justice theory and fairness principles.', ARRAY['Justice as fairness', 'Original position'], 'Framework for determining fair distribution of resources and opportunities.', ARRAY['AI enables fairness at machine speed', 'Scales justice principles'], ARRAY['Implement algorithmic fairness'], ARRAY['Encoding biased notions of fairness'], ARRAY['Fairness metrics', 'Justice outcomes'], ARRAY['How do we ensure AI systems are fair?'], ARRAY['Build fair AI algorithms', 'Implement justice principles'], ARRAY['Isaiah Berlin', 'Amartya Sen'], jsonb_build_object('ai_relevance', 'High - algorithmic fairness'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Amartya Sen', 'Capabilities approach and human development.', ARRAY['Capabilities approach', 'Human development'], 'Framework for evaluating well-being based on capabilities rather than resources.', ARRAY['AI can enhance or reduce human capabilities', 'Requires capability-focused design'], ARRAY['Design AI to enhance human capabilities'], ARRAY['Reducing human agency and capabilities'], ARRAY['Capability enhancement', 'Human development indicators'], ARRAY['How can AI enhance human capabilities?'], ARRAY['Build capability-enhancing AI', 'Measure human development'], ARRAY['John Rawls', 'Martha Nussbaum'], jsonb_build_object('ai_relevance', 'High - human-centered AI'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Martha Nussbaum', 'Human flourishing and capabilities ethics.', ARRAY['Human flourishing', 'Capabilities ethics'], 'Framework for understanding what constitutes a good human life.', ARRAY['AI affects conditions for human flourishing', 'Non-human actors in flourishing'], ARRAY['Design AI to support human flourishing'], ARRAY['Ignoring human flourishing in AI design'], ARRAY['Flourishing indicators', 'Well-being measures'], ARRAY['How can AI support human flourishing?'], ARRAY['Build flourishing-focused AI', 'Measure well-being impacts'], ARRAY['Amartya Sen', 'Isaiah Berlin'], jsonb_build_object('ai_relevance', 'Medium - human-centered design'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Hannah Arendt', 'Political theory and the human condition.', ARRAY['The human condition', 'Political action'], 'Analysis of human activity and the nature of political life.', ARRAY['AI challenges boundaries between labor, work, and action', 'Changes political participation'], ARRAY['Preserve human political agency'], ARRAY['Eliminating human political participation'], ARRAY['Political engagement', 'Human agency preservation'], ARRAY['How does AI affect human political action?'], ARRAY['Preserve political agency', 'Design participatory AI'], ARRAY['Shoshana Zuboff', 'John Rawls'], jsonb_build_object('ai_relevance', 'Medium - political systems'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Kotter & Schlesinger', 'Change management and organizational transformation.', ARRAY['Change strategies', 'Resistance management'], 'Framework for managing organizational change and overcoming resistance.', ARRAY['AI personalizes change management', 'Accelerates transformation'], ARRAY['Use AI to facilitate organizational change'], ARRAY['Ignoring human factors in AI-driven change'], ARRAY['Change success rate', 'Adoption metrics'], ARRAY['How can AI improve change management?'], ARRAY['Implement AI change management', 'Personalize transformation journeys'], ARRAY['Chris Argyris', 'Peter Senge'], jsonb_build_object('ai_relevance', 'Medium - organizational change'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Chris Argyris', 'Organizational learning and double-loop learning.', ARRAY['Double-loop learning', 'Organizational learning'], 'Framework for deep organizational learning and mental model change.', ARRAY['AI accelerates learning loops', 'Enables continuous adaptation'], ARRAY['Design AI for organizational learning'], ARRAY['Bypassing necessary learning processes'], ARRAY['Learning speed', 'Adaptation effectiveness'], ARRAY['How can AI accelerate organizational learning?'], ARRAY['Build AI learning systems', 'Accelerate feedback loops'], ARRAY['Peter Senge', 'Edgar Schein'], jsonb_build_object('ai_relevance', 'Medium - organizational development'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Edgar Schein', 'Organizational culture and cultural change.', ARRAY['Organizational culture', 'Cultural embedding'], 'Framework for understanding and changing organizational culture.', ARRAY['AI becomes part of organizational culture', 'Changes cultural dynamics'], ARRAY['Consider AI impact on culture'], ARRAY['Ignoring cultural integration of AI'], ARRAY['Cultural health', 'AI integration success'], ARRAY['How does AI become part of organizational culture?'], ARRAY['Integrate AI into culture', 'Manage cultural change'], ARRAY['Chris Argyris', 'Simon Sinek'], jsonb_build_object('ai_relevance', 'Medium - cultural integration'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Simon Sinek', 'Purpose-driven leadership and organizational purpose.', ARRAY['Purpose-driven leadership', 'Start with why'], 'Framework for building purpose-driven organizations and leadership.', ARRAY['Purpose must include AI alignment', 'AI affects organizational mission'], ARRAY['Align AI with organizational purpose'], ARRAY['Misaligning AI with organizational values'], ARRAY['Purpose clarity', 'AI-purpose alignment'], ARRAY['How do we align AI with organizational purpose?'], ARRAY['Build purpose-driven AI', 'Integrate AI with mission'], ARRAY['Edgar Schein', 'Jim Collins'], jsonb_build_object('ai_relevance', 'Medium - organizational purpose'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Alvin Toffler', 'Future shock and accelerating change.', ARRAY['Future shock', 'Accelerating change'], 'Theory of psychological stress from rapid technological and social change.', ARRAY['AI compresses shock cycles', 'Daily disruption becomes normal'], ARRAY['Design AI to help humans adapt to change'], ARRAY['Overwhelming users with too much change'], ARRAY['Adaptation rate', 'Stress management'], ARRAY['How do we help people adapt to AI-driven change?'], ARRAY['Build adaptive AI systems', 'Manage change pace'], ARRAY['Ray Kurzweil', 'Kevin Kelly'], jsonb_build_object('ai_relevance', 'Medium - change management'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('William Gibson', 'Cyberpunk futures and technological integration.', ARRAY['Cyberpunk', 'Technological integration'], 'Visionary exploration of human-technology integration and digital futures.', ARRAY['AI flattens prototype-to-deployment gap', 'Accelerates technological integration'], ARRAY['Prepare for rapid AI integration'], ARRAY['Underestimating integration speed'], ARRAY['Integration success', 'Adoption smoothness'], ARRAY['How quickly will AI integrate into daily life?'], ARRAY['Plan for rapid integration', 'Design seamless AI adoption'], ARRAY['Neal Stephenson', 'Kevin Kelly'], jsonb_build_object('ai_relevance', 'Medium - technology futures'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Neal Stephenson', 'Metaverse concepts and virtual economies.', ARRAY['Metaverse', 'Virtual economies'], 'Visionary concepts of virtual worlds and digital economic systems.', ARRAY['AI operationalizes immersive economies', 'Enables persistent virtual worlds'], ARRAY['Design AI for virtual world management'], ARRAY['Ignoring virtual world governance needs'], ARRAY['Virtual economy health', 'User experience'], ARRAY['How will AI manage virtual economies?'], ARRAY['Build AI virtual world systems', 'Design digital economies'], ARRAY['William Gibson', 'Tim O''Reilly'], jsonb_build_object('ai_relevance', 'Medium - virtual systems'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now())),
('Margaret Atwood', 'Speculative fiction and future scenario planning.', ARRAY['Speculative fiction', 'Dystopian scenarios'], 'Exploration of potential futures through narrative and scenario analysis.', ARRAY['AI becomes character in future narratives', 'Shapes story outcomes'], ARRAY['Use speculative methods for AI planning'], ARRAY['Ignoring negative scenario possibilities'], ARRAY['Scenario quality', 'Future preparedness'], ARRAY['What are the worst-case AI scenarios we should prepare for?'], ARRAY['Develop AI scenario planning', 'Prepare for multiple futures'], ARRAY['Yuval Noah Harari', 'William Gibson'], jsonb_build_object('ai_relevance', 'Medium - future planning'), jsonb_build_object('source', 'baseline', 'method', 'bulk-seed', 'seeded_at', now()))
ON CONFLICT (thinker_name) DO UPDATE SET
  summary = EXCLUDED.summary,
  key_concepts = EXCLUDED.key_concepts,
  why_it_matters = EXCLUDED.why_it_matters,
  ai_implications = EXCLUDED.ai_implications,
  recommended_practices = EXCLUDED.recommended_practices,
  common_pitfalls = EXCLUDED.common_pitfalls,
  success_metrics = EXCLUDED.success_metrics,
  usage_prompts = EXCLUDED.usage_prompts,
  practical_applications = EXCLUDED.practical_applications,
  related_thinkers = EXCLUDED.related_thinkers,
  cross_era_relevance = EXCLUDED.cross_era_relevance,
  metadata = EXCLUDED.metadata,
  updated_at = now();